#spring.application.name=spring-web-basic
spring:
  application:
    name: spring-web-basic

server:
  port: 8181

logging:
  level:
    com:
      codeit:
        springwebbasic:
          common:
            log:
              LogExample: trace
  file:
    name: /Users/hyeong-il/Desktop/Codeit/7-develop/logs/app.log

springdoc:
  swagger-ui:
    path: /api-docs-ui.html # UI page 경로
    tags-sorter: alpha # 태그 정렬 방식 (알파벳순)
    operations-sorter: method # 메서드 정렬 방식
    display-request-duration: true # 요청에 소요된 시간 표시
    doc-expansion: list # 문서 펼침 상태 (none, full, list)

  api-docs:
    path: /my-api # Swagger가 우리 API의 정보를 얻어오기 위해서 요청하는 url